services:
  db:
    image: mariadb:11
    container_name: bai3_svc_db
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: bai3db
      MARIADB_USER: demo
      MARIADB_PASSWORD: demo123
    ports:
      - "3308:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  user-service:
    build: ./user-service
    container_name: bai3_user_service
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: demo
      DB_PASSWORD: demo123
      DB_NAME: bai3db
      PORT: 6001
    depends_on:
      - db
    ports:
      - "6001:6001"

  product-service:
    build: ./product-service
    container_name: bai3_product_service
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: demo
      DB_PASSWORD: demo123
      DB_NAME: bai3db
      PORT: 6002
    depends_on:
      - db
    ports:
      - "6002:6002"

  order-service:
    build: ./order-service
    container_name: bai3_order_service
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: demo
      DB_PASSWORD: demo123
      DB_NAME: bai3db
      PORT: 6003
    depends_on:
      - db
    ports:
      - "6003:6003"

  frontend:
    image: nginx:alpine
    container_name: bai3_svc_frontend
    depends_on:
      - user-service
      - product-service
      - order-service
    ports:
      - "8089:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
