# V3: 2 stages, runtime dung distroless toi gian
FROM golang:1.22-alpine AS build
WORKDIR /src
COPY app/go.mod ./
RUN go mod download
COPY app/main.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app ./main.go

FROM gcr.io/distroless/static-debian12
COPY --from=build /app /app
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/app"]
